server:
  port: 3500
  logger: ['error', 'warn', 'debug', 'log', 'verbose']
  protocol: 'http'
  address: 'http://localhost:3500'
  secureStaticPath: '/uploads'
  documentation: '/documentation'

db:
  type: 'postgres'
  port: 5432
  database: 'test'
  cache:
    time: 54000000

jwt:
  expiresIn: 31104000

pagination:
  page: 1
  limit: 10